server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: authuser
    password: authpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource.web: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
